language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - sudo apt-get install -y python-numpy python-scipy python-astropy
install:
  - pip install -r requirements.txt
# command to run tests
script:
  pytest