language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - sudo apt-get install -y python-numpy python-scipy
  - pip install codecov
  - pip install pytest-cov
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov .

after_success:
  - codecov
